version: '2'
services:
  app:
    image: phoenix:1.3.0
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:9
    ports:
      - "5432:5432"
    expose:
      - "5432"
